alias: "Turn on LIFX when lights turned on in bed room."
trigger: 
  platform: state
  entity_id: light.marias_light
  from: "off" 
  to: "on"
action:
  service: light.turn_on
  entity_id:
  - light.bedroom_led_strip_
  data: 
    brightness: 50 
    color_name: cornsilk
  

 
