alias: "Turn off Elins LED strip in the evening"
trigger: 
  platform: time
  at: "19:30:00"
action:
  - service: switch.turn_off
    entity_id:
    - switch.telldusextra_switch
  - service: light.turn_off
    entity_id:
    - light.elins_led_strip
 
