alias: "Bad weather over - lights off!"
trigger: 
  platform: numeric_state
  entity_id: sensor.cloudiness 
  below: 25 
condition: 
  condition: sun 
  before: 'sunset'
  offset: '-1:30:00' 
action: 
  service: light.turn_off
  entity_id:
    - group.livingroom
    - group.bedroom 
    - group.elins_room
    - group.vilhelms_room
    - group.office
 
 
