alias: "Turn on office light at sunset" 
trigger: 
  platform: sun 
  event: sunset
  offset: -01:30:00
action:
  service: switch.turn_on
  entity_id:
  - switch.nodon_msp31xx_micro_smart_plug_switch 


