alias: "Turn on Elins LED strip at sunset" 
trigger: 
  platform: sun 
  event: sunset
  offset: -01:30:00
action:
  service: switch.turn_on
  entity_id:
  - switch.tellduselin_switch
  - switch.telldusextra_switch


