alias: "Turn off Elins LED strip in the evening"
trigger: 
  platform: time
  at: "20:00:00"
action:
  service: switch.turn_off
  entity_id:
  - switch.tellduselin_switch
  - switch.telldusextra_switch

  
 
