alias: "Turn on Elins LED strip at sunset" 
trigger: 
  platform: sun 
  event: sunset
  offset: -01:30:00
action:
  - service: switch.turn_on
    entity_id:
    - switch.telldusextra_switch
  - service: light.turn_on
    entity_id:
    - light.elins_led_strip
    data: 
      brightness: 100
      color_name: brightpink


