alias: "22:00 and Workstation Turned Off" 
trigger: 
  platform: time 
  at: '22:00:00' 
condition:
  condition: state 
  entity_id: device_tracker.workstationcartman 
  state: 'not_home'  
action:
  service: switch.turn_off
  entity_id:
  - switch.nodon_msp31xx_micro_smart_plug_switch
  - switch.telldusextra_switch


