alias: 'Notify that Vilhelm is home' 
trigger: 
  platform: state 
  entity_id: device_tracker.oneplus_x__vilhelm 
  from: 'not_home'
  to: 'home'
action:
  service: notify.pushbullet
  data:
    message: 'Vilhelm is home'
