alias: "Turn on lights at sunset in Kids' room, Living Room and Bedroom"
trigger: 
  platform: sun
  event: sunset 
  offset: -01:00:00
action: 
  service: light.turn_on
  entity_id:
    - group.livingroom
    - group.bedroom 
    - group.elins_room
    - group.vilhelms_room
    - group.hallway
  data: 
    brightness: 150
    color_temp: 458.50527281063734

 
 
